const JOIN_CLASSROOM = "JOIN_CLASSROOM";
const SEND_MESSAGE = "SEND_MESSAGE";
const LEAVE_CLASSROOM = "LEAVE_CLASSROOM";
const CLASSROOM_MESSAGE = "CLASSROOM_MESSAGE";

module.exports = {
  JOIN_CLASSROOM,
  SEND_MESSAGE,
  LEAVE_CLASSROOM,
  CLASSROOM_MESSAGE,
};
